version: '1.0'
services:
   app:
     image: 'rasa/rasa-sdk:latest'
     volumes:
       - './actions:/app/actions'
     expose:
       - '5055'
     depends_on:
       - rasa-production
       
version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: pickoutsports-chatbot-actions:versio-1
    expose: 5055       
       