version: '3.4'
services:
  rasa:
    image: rasa/rasa:latest
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: chefkoch24/pickoutsports-chatbot-actions:version-1
    ports: 
      - 5055:5055